<a href="https://colab.research.google.com/github/mohit747/Deep_learning/blob/main/deepLearning_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(1, activation=tf.nn.relu)
# ReLU=> y=x, if x >0, y=0, if x <=0

model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.mae, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [3]:
model.fit(x,y,epochs=300, verbose=0)
predictions = model.predict(x)
print(predictions)

[[0.        ]
 [0.        ]
 [0.        ]
 [0.04351118]
 [0.38702193]
 [0.04351118]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.04351118]]


In [4]:
model.get_weights()
# trainable_params = input_size * output_size + output_size
# 1 X 1 + 1= 2
# regression neural network

[array([[-0.34351075]], dtype=float32), array([-0.29999956], dtype=float32)]

In [5]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(2)
# ReLU=> y=x, if x >0, y=0, if x <=0
# 0 and 1 -> should be 0th position < 1st position, or vice versa 
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.mae, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [12]:
model.fit(x,y,epochs=100, verbose=0)
predictions = model.predict(x)
#print(predictions)
# First output-> for positives, 1st position-> negative
for prediction in predictions:
  if prediction[0] < prediction[1]:
    print('positive')
  if prediction[0] > prediction[1]:
    print('negative')
  if prediction[0] == prediction[1]:
    print('zero')

positive
positive
zero
negative
negative
negative
zero
positive
positive
positive
zero
negative


In [13]:
predictions

array([[-1.4473116e+00,  5.1209599e-01],
       [-7.2334599e-01,  2.5635779e-01],
       [ 6.1962602e-04,  6.1962602e-04],
       [ 7.2458529e-01, -2.5511855e-01],
       [ 1.4485509e+00, -5.1085669e-01],
       [ 7.2458529e-01, -2.5511855e-01],
       [ 6.1962602e-04,  6.1962602e-04],
       [-7.2334599e-01,  2.5635779e-01],
       [-1.4473116e+00,  5.1209599e-01],
       [-7.2334599e-01,  2.5635779e-01],
       [ 6.1962602e-04,  6.1962602e-04],
       [ 7.2458529e-01, -2.5511855e-01]], dtype=float32)

In [8]:
# users provide 2 entities:
# input set -> parameters
# output set [if missing-> unsupervised learning!]
# anything modified by developers-> hyperparameter
# no. of output dimensions-> i was manipulating!
# loss functions, optimizer functions-> i was adjusting 
# EPOCHS-> how many iterations?

In [14]:
xtest = [ -3, -4, -3, -2, -1, 0]

In [15]:
newpredictions = model.predict(xtest)

In [17]:
for prediction in  newpredictions:
  if prediction[0] < prediction[1]:
    print('positive')
  if prediction[0] > prediction[1]:
    print('negative')
  if prediction[0] == prediction[1]:
    print('zero')

negative
negative
negative
negative
negative
zero


In [18]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(2, activation = tf.nn.softmax)
# ReLU=> y=x, if x >0, y=0, if x <=0
# 0 and 1 -> should be 0th position < 1st position, or vice versa 
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.categorical_crossentropy, optimizer='adam')

In [19]:
predictions = model.predict(x)

In [20]:

predictions

array([[0.92940813, 0.07059187],
       [0.7839468 , 0.2160532 ],
       [0.5       , 0.5       ],
       [0.2160532 , 0.7839468 ],
       [0.07059187, 0.92940813],
       [0.2160532 , 0.7839468 ],
       [0.5       , 0.5       ],
       [0.7839468 , 0.2160532 ],
       [0.92940813, 0.07059187],
       [0.7839468 , 0.2160532 ],
       [0.5       , 0.5       ],
       [0.2160532 , 0.7839468 ]], dtype=float32)

In [21]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(1, activation = tf.nn.tanh)
# tanh=> from -1 to +1 
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.categorical_crossentropy, optimizer='adam')

In [22]:

predictions = model.predict(x)
predictions

array([[-0.9928201],
       [-0.8867492],
       [ 0.       ],
       [ 0.8867492],
       [ 0.9928201],
       [ 0.8867492],
       [ 0.       ],
       [-0.8867492],
       [-0.9928201],
       [-0.8867492],
       [ 0.       ],
       [ 0.8867492]], dtype=float32)

In [23]:
for prediction in predictions:
  if prediction > 0:
    print ('pos')
  if prediction < 0:
    print ('neg')
  if prediction == 0:
    print ('zero')

neg
neg
zero
pos
pos
pos
zero
neg
neg
neg
zero
pos


In [24]:
# ReLU-> y =  x if x>0, y=0 if x<=0 
# SoftMax-> probab distribution => sum(all_elements) = 1
# TanH-> -1 to 1
# tan => pi/2-> inf and -pi/2-> inf
# tanh-> tan -> 90 deg rotation 
# tanh -> pi/2 and -pi/2 -> 1 and -1 respectively
#        x axis takes infinity!

In [25]:
# tanh scaled b/w 0 to 1
# Probability-> Sigmoid
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(1, activation = tf.nn.sigmoid)
# tanh=> from -1 to +1 
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.categorical_crossentropy, optimizer='adam')

In [26]:
predictions = model.predict(x)
predictions


array([[0.2729602],
       [0.3799342],
       [0.5      ],
       [0.6200658],
       [0.7270398],
       [0.6200658],
       [0.5      ],
       [0.3799342],
       [0.2729602],
       [0.3799342],
       [0.5      ],
       [0.6200658]], dtype=float32)

In [27]:
for prediction in predictions:
  if prediction < 0.5:
    print ('pos')
  if prediction > 0.5:
    print ('neg')
  if prediction == 0.5:
    print ('zero')

pos
pos
zero
neg
neg
neg
zero
pos
pos
pos
zero
neg


In [28]:
# normalization
# my general guideline!
# probability (distribution/multi-classification)-> softmax 
# profit/loss/comparisons-> tanh
# regressions/color/no-neg nos. allowed-> ReLU
# binary classification -> sigmoid