<a href="https://colab.research.google.com/github/mohit747/Deep_learning/blob/main/Deeplearning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Agenda-> Neural Networks
# Tensorflow
# TF 2.x 

# Computer Vision
# Natural LP
# SIGNAL

In [ ]:

import tensorflow as tf

In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8, 9 ,10])
y = np.array([0,1,0,1,0,1,0,1,0,1])

In [ ]:
from tensorflow import keras

In [ ]:
layer1 = keras.layers.Dense(1)

In [ ]:
model = keras.models.Sequential([layer1])

In [ ]:
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [ ]:
history = model.fit(x, y, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 641ms/step - loss: 1.6502 - mean_squared_error: 1.6502
Epoch 2/50
1/1 [==============================] - 0s 6ms/step - loss: 1.6334 - mean_squared_error: 1.6334
Epoch 3/50
1/1 [==============================] - 0s 7ms/step - loss: 1.6167 - mean_squared_error: 1.6167
Epoch 4/50
1/1 [==============================] - 0s 7ms/step - loss: 1.6002 - mean_squared_error: 1.6002
Epoch 5/50
1/1 [==============================] - 0s 4ms/step - loss: 1.5837 - mean_squared_error: 1.5837
Epoch 6/50
1/1 [==============================] - 0s 7ms/step - loss: 1.5674 - mean_squared_error: 1.5674
Epoch 7/50
1/1 [==============================] - 0s 9ms/step - loss: 1.5511 - mean_squared_error: 1.5511
Epoch 8/50
1/1 [==============================] - 0s 10ms/step - loss: 1.5350 - mean_squared_error: 1.5350
Epoch 9/50
1/1 [==============================] - 0s 7ms/step - loss: 1.5190 - mean_squared_error: 1.5190
Epoch 10/50
1/1 [==========================

In [ ]:
history.history['loss']

[1.6501939296722412,
 1.6334171295166016,
 1.616743803024292,
 1.6001758575439453,
 1.5837154388427734,
 1.5673637390136719,
 1.5511223077774048,
 1.5349925756454468,
 1.5189769268035889,
 1.5030759572982788,
 1.4872913360595703,
 1.471624493598938,
 1.4560766220092773,
 1.4406487941741943,
 1.425342321395874,
 1.410158395767212,
 1.3950977325439453,
 1.3801615238189697,
 1.365350365638733,
 1.3506650924682617,
 1.3361066579818726,
 1.3216753005981445,
 1.3073720932006836,
 1.2931970357894897,
 1.2791509628295898,
 1.2652339935302734,
 1.2514463663101196,
 1.2377887964248657,
 1.224260687828064,
 1.2108628749847412,
 1.1975951194763184,
 1.1844574213027954,
 1.171449899673462,
 1.1585719585418701,
 1.1458241939544678,
 1.133205771446228,
 1.1207168102264404,
 1.1083567142486572,
 1.096125602722168,
 1.0840227603912354,
 1.0720478296279907,
 1.060200572013855,
 1.0484802722930908,
 1.0368865728378296,
 1.025418996810913,
 1.0140769481658936,
 1.0028597116470337,
 0.9917667508125305,
 0.

In [ ]:
model.summary()
# y = w1 * x + bias
# trainable params-> 2

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.get_weights()

[array([[-0.06371816]], dtype=float32), array([0.04803257], dtype=float32)]

In [ ]:
predictedvalues = model.predict(x)

In [ ]:
predictedvalues

array([[-0.0156856 ],
       [-0.07940376],
       [-0.14312191],
       [-0.20684008],
       [-0.27055824],
       [-0.33427638],
       [-0.39799458],
       [-0.46171272],
       [-0.52543086],
       [-0.58914906]], dtype=float32)

In [ ]:
layer1 = keras.layers.Dense(10)
layer2 = keras.layers.Dense(1)
model = keras.models.Sequential([layer1, layer2])
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [ ]:
history = model.fit(x, y, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 411ms/step - loss: 7.2352 - mean_squared_error: 7.2352
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 7.0198 - mean_squared_error: 7.0198
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 6.8084 - mean_squared_error: 6.8084
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 6.6009 - mean_squared_error: 6.6009
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 6.3973 - mean_squared_error: 6.3973
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 6.1978 - mean_squared_error: 6.1978
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 6.0024 - mean_squared_error: 6.0024
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 5.8111 - mean_squared_error: 5.8111
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 5.6238 - mean_squared_error: 5.6238
Epoch 10/100
1/1 [=================

In [ ]:
model.summary()
# broken numbers

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                20        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [ ]:

y = model.predict(x)

In [ ]:
y

array([[0.26137745],
       [0.28293633],
       [0.30449513],
       [0.32605395],
       [0.34761274],
       [0.36917153],
       [0.39073056],
       [0.4122891 ],
       [0.43384767],
       [0.4554067 ]], dtype=float32)

In [ ]:
# 3 Layer- Fully Connected- Neural Network
layer1 = keras.layers.Dense(8)
layer2 = keras.layers.Dense(256)
layer3 = keras.layers.Dense(1)
model = keras.models.Sequential([layer1, layer2, layer3])
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [ ]:
history = model.fit(x, y, epochs=100, verbose=0) # dont show output here
predictions = model.predict(x)
predictions

array([[0.2632034 ],
       [0.2841118 ],
       [0.30502015],
       [0.32592848],
       [0.34683686],
       [0.36774516],
       [0.38865352],
       [0.40956175],
       [0.4304702 ],
       [0.45137835]], dtype=float32)

In [ ]:
print(model.get_weights())

[array([[-0.56926155,  0.3150539 , -0.39617297, -0.01670024, -0.7971028 ,
        -0.3520857 ,  0.32325637,  0.01765651]], dtype=float32), array([-0.00371803,  0.01013493, -0.00961919,  0.00040853,  0.01259252,
       -0.00959744, -0.01437599, -0.0124664 ], dtype=float32), array([[ 0.0863228 , -0.1250684 , -0.1337608 , ..., -0.02052481,
         0.01787866, -0.06624793],
       [ 0.12108993, -0.02491543,  0.0592386 , ...,  0.1441855 ,
         0.04882611,  0.10317537],
       [-0.10446347,  0.10489257,  0.0453778 , ...,  0.08950806,
         0.02030642,  0.04669547],
       ...,
       [ 0.06422826,  0.12293202, -0.02676099, ...,  0.00652668,
        -0.07011507,  0.12309703],
       [ 0.09111975, -0.07716595,  0.09616631, ...,  0.00114058,
         0.00581763, -0.02389668],
       [-0.10538518,  0.13752666, -0.09337526, ..., -0.13057086,
        -0.11519385, -0.02913094]], dtype=float32), array([-0.01111387, -0.01107822, -0.0112228 , -0.0107106 ,  0.01127314,
       -0.01147984, -0.01